[package]
name = "offchain-core"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
ethabi = { version = "14.0.0", default-features = false }
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "4690f8e" }
