[package]
name = "offchain-core"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
ethabi = { version = "14.0.0", default-features = false }
ethers = { version = "0.5.3", features = [ "ws" ] }
