[package]
name = "backoff"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
rand = "0.8.0"
tokio = { version = "^1.5", features = ["time"] }

[dev-dependencies]
tokio = { version = "^1.5", features = ["macros"] }
