# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code Format
on: [push]
jobs:
    fmt:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: cargo fmt --all -- --check
